"""create addon_groups and addons tables

Revision ID: 11aa25d907f3
Revises: f13cab7f836a
Create Date: 2026-04-21 18:19:40.293997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11aa25d907f3'
down_revision: Union[str, Sequence[str], None] = 'f13cab7f836a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon_groups',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('min_selections', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_selections', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('single', 'multiple')", name=op.f('ck_addon_groups_type')),
    sa.CheckConstraint('max_selections >= min_selections', name=op.f('ck_addon_groups_max_selections_gte_min')),
    sa.CheckConstraint('min_selections >= 0', name=op.f('ck_addon_groups_min_selections_non_negative')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_addon_groups_store_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addon_groups'))
    )
    op.create_index('ix_addon_groups_store_id', 'addon_groups', ['store_id'], unique=False)
    op.create_table('addons',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_cents >= 0', name=op.f('ck_addons_price_cents_non_negative')),
    sa.ForeignKeyConstraint(['group_id'], ['addon_groups.id'], name=op.f('fk_addons_group_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addons'))
    )
    op.create_index('ix_addons_group_id', 'addons', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addons_group_id', table_name='addons')
    op.drop_table('addons')
    op.drop_index('ix_addon_groups_store_id', table_name='addon_groups')
    op.drop_table('addon_groups')
    # ### end Alembic commands ###
