"""create stores table

Revision ID: 248dec4751ff
Revises: cd2dbc905b1a
Create Date: 2026-04-21 16:57:56.967921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248dec4751ff'
down_revision: Union[str, Sequence[str], None] = 'cd2dbc905b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=14), nullable=False),
    sa.Column('tax_id_type', sa.String(length=4), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'blocked', 'paused')", name=op.f('ck_stores_status')),
    sa.CheckConstraint("tax_id_type IN ('cpf', 'cnpj')", name=op.f('ck_stores_tax_id_type')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_stores_category_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_stores_city_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('slug', name=op.f('uq_stores_slug')),
    sa.UniqueConstraint('tax_id', name=op.f('uq_stores_tax_id'))
    )
    op.create_index('ix_stores_category_id', 'stores', ['category_id'], unique=False)
    op.create_index('ix_stores_city_id', 'stores', ['city_id'], unique=False)
    op.create_index('ix_stores_status', 'stores', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stores_status', table_name='stores')
    op.drop_index('ix_stores_city_id', table_name='stores')
    op.drop_index('ix_stores_category_id', table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
