"""create order_item_addons table

Revision ID: 9fc0a1ebd6ab
Revises: 9235020fd72d
Create Date: 2026-04-22 00:33:35.941484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc0a1ebd6ab'
down_revision: Union[str, Sequence[str], None] = '9235020fd72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_addons',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('addon_id', sa.Uuid(), nullable=False),
    sa.Column('addon_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('unit_price_cents >= 0', name=op.f('ck_order_item_addons_unit_price_cents_non_negative')),
    sa.ForeignKeyConstraint(['addon_id'], ['addons.id'], name=op.f('fk_order_item_addons_addon_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_order_item_addons_order_item_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_item_addons'))
    )
    op.create_index('ix_order_item_addons_addon_id', 'order_item_addons', ['addon_id'], unique=False)
    op.create_index('ix_order_item_addons_order_item_id', 'order_item_addons', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_item_addons_order_item_id', table_name='order_item_addons')
    op.drop_index('ix_order_item_addons_addon_id', table_name='order_item_addons')
    op.drop_table('order_item_addons')
    # ### end Alembic commands ###
