"""create product_addon_groups junction table

Revision ID: c19dc1358909
Revises: 11aa25d907f3
Create Date: 2026-04-21 18:43:57.810675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19dc1358909'
down_revision: Union[str, Sequence[str], None] = '11aa25d907f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_addon_groups',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['addon_groups.id'], name=op.f('fk_product_addon_groups_group_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_addon_groups_product_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_addon_groups')),
    sa.UniqueConstraint('product_id', 'group_id', name='uq_product_addon_groups_product_id_group_id')
    )
    op.create_index('ix_product_addon_groups_group_id', 'product_addon_groups', ['group_id'], unique=False)
    op.create_index('ix_product_addon_groups_product_id', 'product_addon_groups', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_addon_groups_product_id', table_name='product_addon_groups')
    op.drop_index('ix_product_addon_groups_group_id', table_name='product_addon_groups')
    op.drop_table('product_addon_groups')
    # ### end Alembic commands ###
