"""create orders table

Revision ID: ce147e4e4268
Revises: c19dc1358909
Create Date: 2026-04-21 21:01:23.665262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce147e4e4268'
down_revision: Union[str, Sequence[str], None] = 'c19dc1358909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('public_id', sa.String(length=12), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('customer_name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('delivery_address_line1_snapshot', sa.String(length=200), nullable=False),
    sa.Column('delivery_address_line2_snapshot', sa.String(length=200), nullable=True),
    sa.Column('delivery_neighborhood_snapshot', sa.String(length=100), nullable=False),
    sa.Column('delivery_city_snapshot', sa.String(length=100), nullable=False),
    sa.Column('delivery_state_snapshot', sa.String(length=2), nullable=False),
    sa.Column('delivery_postal_code_snapshot', sa.String(length=9), nullable=False),
    sa.Column('delivery_reference_snapshot', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('delivery_fee_cents', sa.Integer(), nullable=False),
    sa.Column('service_fee_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('coupon_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('payment_gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'canceled', 'payment_failed')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('delivery_fee_cents >= 0', name=op.f('ck_orders_delivery_fee_cents_non_negative')),
    sa.CheckConstraint('discount_cents >= 0', name=op.f('ck_orders_discount_cents_non_negative')),
    sa.CheckConstraint('service_fee_cents >= 0', name=op.f('ck_orders_service_fee_cents_non_negative')),
    sa.CheckConstraint('subtotal_cents >= 0', name=op.f('ck_orders_subtotal_cents_non_negative')),
    sa.CheckConstraint('total_cents >= 0', name=op.f('ck_orders_total_cents_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_orders_store_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('public_id', name='uq_orders_public_id')
    )
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_store_id', 'orders', ['store_id'], unique=False)
    op.create_index('uq_orders_payment_gateway_transaction_id', 'orders', ['payment_gateway_transaction_id'], unique=True, postgresql_where=sa.text('payment_gateway_transaction_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_orders_payment_gateway_transaction_id', table_name='orders', postgresql_where=sa.text('payment_gateway_transaction_id IS NOT NULL'))
    op.drop_index('ix_orders_store_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
