"""create addresses table

Revision ID: d1797ce9df3e
Revises: 6ebc0349ab8c
Create Date: 2026-04-21 15:55:37.563594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1797ce9df3e'
down_revision: Union[str, Sequence[str], None] = '6ebc0349ab8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('address_type', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=8), nullable=False),
    sa.Column('reference_point', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("address_type IN ('home', 'work', 'other')", name=op.f('ck_addresses_address_type')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_addresses_city_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_addresses_customer_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index('ix_addresses_city_id', 'addresses', ['city_id'], unique=False)
    op.create_index('ix_addresses_customer_id', 'addresses', ['customer_id'], unique=False)
    op.create_index('uq_addresses_customer_default', 'addresses', ['customer_id'], unique=True, postgresql_where='is_default = true AND deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_addresses_customer_default', table_name='addresses', postgresql_where='is_default = true AND deleted_at IS NULL')
    op.drop_index('ix_addresses_customer_id', table_name='addresses')
    op.drop_index('ix_addresses_city_id', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
