"""create order_status_logs table

Revision ID: e16e2e9ee921
Revises: 9fc0a1ebd6ab
Create Date: 2026-04-22 18:04:52.647125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16e2e9ee921'
down_revision: Union[str, Sequence[str], None] = '9fc0a1ebd6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'canceled', 'payment_failed')", name=op.f('ck_order_status_logs_from_status_valid')),
    sa.CheckConstraint("to_status IN ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'canceled', 'payment_failed')", name=op.f('ck_order_status_logs_to_status_valid')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_logs_order_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_logs'))
    )
    op.create_index('ix_order_status_logs_order_id', 'order_status_logs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_status_logs_order_id', table_name='order_status_logs')
    op.drop_table('order_status_logs')
    # ### end Alembic commands ###
